project_id = "kdwxmroxfbhmwxkyniph"

[functions.send-to-make]
verify_jwt = true

[functions.meta-oauth-callback]
verify_jwt = false

[functions.meta-api]
verify_jwt = true

[functions.meta-webhook]
verify_jwt = false

[functions.meta-token-refresh]
verify_jwt = true
