// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdwxmroxfbhmwxkyniph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtkd3htcm94ZmJobXd4a3luaXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODIyNTIsImV4cCI6MjA3Mzk1ODI1Mn0.8Nehpt4rQmiLIS5OJ-NJAP-gDc7AiURXgpjX0KgFTJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});